### ISSUE TITLE
use test as sync function

### ISSUE THREAD

**Issue by mnlbox** [chill117/proxy-verifier#18]
Hi @chill117 ,
I try using this library for check some proxies but after some check it's return Maximum number of open connections reached. message.
How we can use test function as sync function.
Can you help me?

**Comment by chill117** [comment]
When you test a single proxy, the most number of connections at once would be 6 or so. Are you testing all of your proxies in parallel?

**Comment by mnlbox** [comment]
No I use a foreach for check a proxy list.

**Comment by chill117** [comment]
Are you doing something like this?
```js
// !! Do not use this code !!
for (var proxy in proxies) {
    ProxyVerifier.testAll(proxy, function(error, result) {
    });
}
```
Because this would lead to the issue you're having. The problem with the above code is that the loop *starts* the testing for each proxy without waiting for the previous tests to finish. So you will end up with ~6 simultaneously open HTTP requests *per* proxy.
