### ISSUE TITLE
Pass request option in Test function

### ISSUE THREAD

**Issue by mnlbox** [chill117/proxy-verifier#19]
Is it possible to set [request](https://github.com/request/request) options in [Test](https://github.com/chill117/proxy-verifier#test) function like `testAll` and other functions?
I can't see related note in docs. I want to increase request connection timeout value. Can you guide me about it?

**Comment by chill117** [comment]
Yes, this is possible. You can use the `requestOptions` option, like this:
```js
ProxyVerifier.test(proxy, {
    requestOptions: {
        // request options go here.
    },
    testUrl: 'https://www.google.com/?q=test',
    testFn: function(data, status, headers) {

        // Check the response data, status, and headers.

        // Throw an error if the test failed.
        throw new Error('Test failed!');

        // Do nothing if the test passed.
    }
}, function(error, results) {
    // Do something with error or results.
});
```
