### ISSUE TITLE
How does this module works? Does it submit proxies to bitproxies.eu to SELL them?

### ISSUE THREAD

**Issue by dave7280** [chill117/proxy-verifier#25]
Does this volume checks socks5 LOCALLY, or does it submit proxies to external service? As i see some references to external services in the code.

```
	_defaultTestUrl: 'http://bitproxies.eu/api/v2/check',
	_ipAddressCheckUrl: 'https://bitproxies.eu/api/v2/check',
	_tunnelTestUrl: 'https://bitproxies.eu/api/v2/check',
```

Bitproxies.eu:

Fast, easy API access to a large database of verified, active proxies (http, https, socks)

So could you clarify whether you submit **proxies of library users** to service where they're **resold**?

**Comment by chill117** [comment]
The HTTPS API at https://bitproxies.eu/api/v2/check reflects the headers sent to the web server. It doesn't store any information. But I do understand your concerns. I started a [work-in-progress branch](https://github.com/chill117/proxy-verifier/tree/local-proxy-check-with-ngrok) that removes the remote HTTPS calls, but I have not had time to finish it.

**Comment by chill117** [comment]
Latest version of this module uses https://ifconfig.me as the proxy check service, so no longer dependent on the now offline bitproxies.eu service.
