### ISSUE TITLE
It doesnt work anymore.

### ISSUE THREAD

**Issue by AlMuz** [chill117/proxy-verifier#26]
Looks like your domain bitproxies.eu died and verifier doesnt work anymore..

**Comment by chill117** [comment]
Thanks for the heads-up. I am working to restore the domain and the checking service now.

I have a work-in-progress branch of this module that removes this remote dependency, but I haven't had time to finish it. Hopefully in the coming weeks I will.

**Comment by azakero** [comment]
Hey, for some proxies I get the result right away. But for others, I get errors after a long time or I don't get anything at all(keeps on loading). Is it supposed to work like this?

**Comment by sepatin** [comment]
@chill117 Thanks for your great tool ! 
Did you have time to finalize your PR and do you plan to merge it quickly ?

**Comment by vladislav-puzyrev** [comment]
+1

**Comment by chill117** [comment]
I shutdown the remote service because it was receiving too much traffic for my server to handle. I don't have time to work on this at the moment. But there is that work-in-progress branch that I started, in case anyone wants to give it a go.

**Comment by chill117** [comment]
Latest version of this module uses https://ifconfig.me as the proxy check service, so no longer dependent on the now offline bitproxies.eu service.
