### ISSUE TITLE
default ip leads to malware/bitcoin mining software

### ISSUE THREAD

**Issue by static660** [chill117/proxy-verifier#33]
We blocked this dangerous page for your protection:
http://bitproxies.eu/api/v2/check
Accessed by: node.exe
Threat name: Application.CoinMiner.AY

Explain this to me.

**Comment by chill117** [comment]
Your connection was probably MITM'd. The "http://" protocol means the HTTP traffic is transmitted in plaintext. The latest version of this module uses https://ifconfig.me as the default proxy check service. So this attack vector should be mitigated.
